---
- name: Ensure zsh is the default shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Ensure directories for configs are present
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - { path: "{{ home }}/.config" }

- name: Copy dotfiles to destination
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - { src: .zshrc, dest: "{{ home }}/.zshrc", mode: '0644' }
    - { src: .config/starship.toml, dest: "{{ home }}/.config/starship.toml", mode: '0644' }
    - { src: .config/kitty, dest: "{{ home }}/.config", mode: '0755' }
    - { src: .config/hypr, dest: "{{ home }}/.config", mode: '0755' }
    - { src: .config/swaylock, dest: "{{ home }}/.config", mode: '0755' }
    - { src: .config/dunst, dest: "{{ home }}/.config", mode: '0755' }

- name: Configure greetd config.
  ansible.builtin.blockinfile:
    path: /etc/greetd/config.toml
    block: |
      [initial_session]
      command = "Hyprland"
      user = "manav"
    marker: "# {mark} ANSIBLE MANAGED BLOCK greetd"
    insertafter: EOF
    state: present
