---
- name: Setup base Arch Linux system
  hosts: all

  pre_tasks:
    - name: Ensure package cache is up-to-date
      community.general.pacman:
        update_cache: true
      changed_when: false

  roles:
    - base
    - devsec.hardening.ssh_hardening
