---
- name: Setup hyprland for Arch Linux
  hosts: all

  pre_tasks:
    - name: Ensure package cache is up-to-date
      community.general.pacman:
        update_cache: true
      changed_when: false

  roles:
    - hyprland
